### ISSUE TITLE
Having Problem with HasManyThrough Relationship

### ISSUE THREAD

**Issue by Areebsofyrus** [backspacerhino/adonis-soft-deletes#5]
If i define hasManyThrough reltion on my model and try to delete data using relationship then i got error

**Comment by Areebsofyrus** [comment]
![image](https://user-images.githubusercontent.com/74649877/113480226-ef026a80-94b0-11eb-91f5-6662d40e99d7.png)
This is the error

**Comment by Areebsofyrus** [comment]
Here i have a hasManyThrough relation namely users in company model

Company->brandmanager->user  

below is the code of relation


users() {
    return this.manyThrough('App/Models/BrandManager', 'user')
  }

**Comment by backspacerhino** [comment]
Hi,

This was a known issue ( but as I see now, I have not written anything related to it in the README). 
I checked on what exactly was the issue and found that the error was ambiguous field for me. I was unable to get the error your screenshot displays.

I made some changes to the package to make it work with manyThrough. Due to a breaking change from v2.x I had to move it to v3.0.0 so please update your package. Don't forget to read the updated README.

Please keep in mind that this package is for Adonis v4 and there are some workarounds to make it work with that version. I would strongly advise that you move to v5 due to better codebase/support. With that being said, I will no longer support this package for v4 but I will try to recreate it for v5.
